// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6wfLBgXxF_8n7I0Ff0uT6IqU8GmIh0Cg',
    appId: '1:377550279656:web:4ee50b67fea9623ac1ca5d',
    messagingSenderId: '377550279656',
    projectId: 'crudfirebase-9d699',
    authDomain: 'crudfirebase-9d699.firebaseapp.com',
    storageBucket: 'crudfirebase-9d699.appspot.com',
    measurementId: 'G-YKM8J72HRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xMGRw7wFZhTYb2DPWyYttriE9gKeJsM',
    appId: '1:377550279656:android:103b6a578e88150bc1ca5d',
    messagingSenderId: '377550279656',
    projectId: 'crudfirebase-9d699',
    storageBucket: 'crudfirebase-9d699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB72Xx2y-DfiriIqZM7ptz9TCATAUhuB3g',
    appId: '1:377550279656:ios:c2052debe159e0a8c1ca5d',
    messagingSenderId: '377550279656',
    projectId: 'crudfirebase-9d699',
    storageBucket: 'crudfirebase-9d699.appspot.com',
    iosClientId: '377550279656-rfel5doeu5u676jnesqk7e5v82timlle.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB72Xx2y-DfiriIqZM7ptz9TCATAUhuB3g',
    appId: '1:377550279656:ios:c2052debe159e0a8c1ca5d',
    messagingSenderId: '377550279656',
    projectId: 'crudfirebase-9d699',
    storageBucket: 'crudfirebase-9d699.appspot.com',
    iosClientId: '377550279656-rfel5doeu5u676jnesqk7e5v82timlle.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfirebase',
  );
}
